spring:
  datasource:
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_OAUTH_ID}
            client-secret: ${GOOGLE_OAUTH_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            client-name: naver
            client-id: ${NAVER_OAUTH_ID}
            client-secret: ${NAVER_OAUTH_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
              - profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
oauth2:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth # 고정값
    client:
      id: ${GOOGLE_OAUTH_ID} # 구글 개발자 콘솔에서 발급받은 Client ID
      secret: ${GOOGLE_OAUTH_SECRET} # 구글 개발자 콘솔에서 발급받은 Client Secret
    callback:
      url: http://localhost:8080/login/oauth2/code/google # 유저 설정에 따라 변경 가능 (Redirect URI)
    token:
      url: https://oauth2.googleapis.com/token
    resource:
      url: https://www.googleapis.com/oauth2/v2/userinfo